### ISSUE TITLE
goss audit with run_audit.ps1 script results in >600 out 661 failures

### ISSUE THREAD

**Issue by Sergong** [ansible-lockdown/Windows-2019-CIS-Audit#1]
When running the `run_audit.ps1` script on a Windows 2019 host that was remediated with the Windows-2019-CIS role using all defaults except for the following:
```yaml
win19cis_skip_for_ansible: true
```

I'm getting the following result:
```
        "summary-line": "Count: 661, Failed: 649, Duration: 445.400s",
```

The failures are always as follows:
```
        "err": "Command execution timed out (10s)",
```

This happens even with adding a `timeout: 30000` line to the command in any of the yml files in the `Windows-2019-CIS-Audit` folder structure. Example:

```
  {{ if .Vars.win2019cis_2_3_10_5 }}
  disable_everyone_inc_anon:
    title: 2.3.10.5 | L1 | Ensure 'Network access - Let Everyone permissions apply to anonymous users' is set to 'Disabled' | reg_check
    exec:  {{ .Vars.ps_regcheck }} {{ .Vars.HKLM_CCS_LSA }} -Name EveryoneIncludesAnonymous
    exit-status: 0
    timeout: 30000
    stdout:
    - '1'
    meta:
      Domain_Controller: 1
      Member_Server: 1
      CIS_ID: 2.3.10.5
      CISv8:
      - 4.1
      CISv8_IG1: true
      CISv8_IG2: true
      CISv8_IG3: true
  {{ end }}
```

Note that this is using goss version 3.22 as 3.6 is no longer available for Windows.
